#!/usr/bin/env python3
"""Canonical generator for four integration figures; never regenerates older assets.

Technical contract: Kafka Connect logical paths (SMT when configured), a
consistent PostgreSQL initial snapshot with retained WAL, and at-least-once
outbox delivery with destination-local event-ID deduplication. See Kafka wiki
chapters 14–16. Only the Python standard library is required.
"""
from html import escape
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "assets/images/kafka-textbook"
BG, INK, LINE, WHITE = "#fbfaf6", "#26262b", "#555b6b", "#ffffff"
FONT = "'Apple SD Gothic Neo', 'Noto Sans KR', system-ui, sans-serif"


class Figure:
    def __init__(self, name, height, title, desc):
        self.name, self.height = name, height
        self.prefix = Path(name).stem
        p = self.prefix
        self.header = [
            '<?xml version="1.0" encoding="UTF-8"?>',
            '<!-- Generated by scripts/generation/kafka_integration_diagrams.py -->',
            f'<svg xmlns="http://www.w3.org/2000/svg" width="360" height="{height}" viewBox="0 0 360 {height}" role="img" aria-labelledby="{p}-title {p}-desc">',
            f'<title id="{p}-title">{escape(title)}</title>',
            f'<desc id="{p}-desc">{escape(desc)}</desc>',
            f'<defs><marker id="{p}-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto" markerUnits="userSpaceOnUse"><path d="M 0 0 L 8 4 L 0 8 Z" fill="{LINE}"/></marker></defs>',
            f'<rect width="360" height="{height}" fill="{BG}"/>',
        ]
        self.boundaries, self.edges, self.nodes, self.labels = [], [], [], []

    def text(self, x, y, text, size=15, bold=False, anchor="middle", color=INK):
        self.labels.append(f'<text x="{x}" y="{y}" font-family="{FONT}" font-size="{size}" font-weight="{600 if bold else 400}" text-anchor="{anchor}" fill="{color}" stroke="{BG}" stroke-width="5" stroke-linejoin="round" paint-order="stroke fill">{escape(text)}</text>')

    def box(self, x, y, w, h, lines, boundary=False, dashed=False):
        attrs = ' stroke-dasharray="6 4"' if dashed else ''
        layer = self.boundaries if boundary else self.nodes
        layer.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="8" fill="{BG if boundary else WHITE}" stroke="{LINE}" stroke-width="1.5"{attrs}/>')
        for i, line in enumerate(lines):
            self.text(x + w / 2, y + 24 + i * 24, line, bold=(i == 0))

    def arrow(self, points, dashed=False, head=True):
        d = "M " + " L ".join(f"{x} {y}" for x, y in points)
        attrs = ' stroke-dasharray="5 4"' if dashed else ''
        if head:
            attrs += f' marker-end="url(#{self.prefix}-arrow)"'
        self.edges.append(f'<path d="{d}" fill="none" stroke="{LINE}" stroke-width="1.5" stroke-linejoin="round"{attrs}/>')

    def save(self):
        content = "\n".join(self.header + self.boundaries + self.edges + self.nodes + self.labels + ["</svg>", ""])
        ET.fromstring(content)
        OUT.mkdir(parents=True, exist_ok=True)
        (OUT / self.name).write_text(content, encoding="utf-8")
        print(OUT / self.name)


def runtime():
    f = Figure("fig-14-connect-runtime.svg", 784, "Kafka Connect의 실행 경계", "외부 PostgreSQL에서 source worker JVM의 task가 읽어 Kafka로 보내고, 별도 sink worker JVM의 task가 Kafka에서 읽어 검색 엔진에 쓴다. 이 배치 예시에서 두 worker는 별도 프로세스이며 브로커는 커넥터 플러그인을 실행하지 않는다.")
    f.text(180, 32, "Kafka Connect 실행 경계", 18, True)
    f.text(180, 56, "선은 데이터 이동 · 상자는 실행 위치", 14)
    f.box(40, 84, 280, 64, ["외부 DB · PostgreSQL", "원본 주문을 보관"])
    f.box(40, 192, 280, 112, ["Source worker · JVM A", "Source task가 외부 DB를 읽음", "커넥터 플러그인은 worker에서 실행"], boundary=True)
    f.box(40, 352, 280, 88, ["Kafka 브로커 · 별도 프로세스", "레코드 저장·복제·전달", "커넥터 플러그인을 실행하지 않음"])
    f.box(40, 488, 280, 112, ["Sink worker · JVM B", "Sink task가 Kafka를 읽어 외부 쓰기", "커넥터 플러그인은 worker에서 실행"], boundary=True)
    f.box(40, 648, 280, 64, ["외부 목적지 · 검색 엔진", "주문 검색 문서를 반영"])
    for start, end, label in [(148,192,"외부 읽기"),(304,352,"Kafka로 발행"),(440,488,"Kafka에서 소비"),(600,648,"외부 쓰기")]:
        f.arrow([(180,start),(180,end)])
        f.text(196, (start+end)/2+5, label, 14, anchor="start")
    f.text(180, 740, "서로 다른 worker에 배치한 예시다.", 14)
    f.text(180, 764, "같은 worker에 함께 배치하는 것도 가능하다.", 14)
    f.save()


def record_path():
    f = Figure("fig-14-connect-record-path.svg", 804, "Source와 Sink의 Connect 레코드 경로", "두 레인은 서로 다른 논리적 데이터 경로다. Source는 외부 DB, source task의 SourceRecord, SMT, converter, producer, Kafka 순서다. Sink는 Kafka, consumer, converter, SMT, SinkRecord를 받는 sink task, 외부 목적지 순서다. Task와 변환 및 Kafka 클라이언트는 worker JVM 안에서 실행된다. SMT는 구성한 경우 적용된다.")
    f.text(180, 32, "Connect 레코드의 두 방향", 18, True)
    f.text(180, 56, "각 레인을 위에서 아래로 읽는다.", 14)
    f.text(96, 88, "Source · 외부 → Kafka", 15, True)
    f.text(264, 88, "Sink · Kafka → 외부", 15, True)
    for x in (20,188):
        f.box(x, 200, 152, 428, [], boundary=True, dashed=True)
        f.text(x+76, 224, "Worker JVM 안", 15, True)
    left = [(112,72,["외부 DB","원본 읽기"]),(244,80,["Source task","SourceRecord 생성"]),(348,72,["SMT","레코드 변환"]),(444,80,["converter","키·값 직렬화"]),(548,64,["producer","바이트 발행"]),(656,72,["Kafka","바이트 저장"])]
    right = [(112,72,["Kafka","바이트 읽기"]),(244,80,["consumer","바이트 수신"]),(348,72,["converter","키·값 역직렬화"]),(444,80,["SMT","레코드 변환"]),(548,64,["Sink task","SinkRecord 받음"]),(656,72,["외부 목적지","task가 외부 쓰기"])]
    for x, stages in [(24,left),(192,right)]:
        for y,h,lines in stages:
            f.box(x,y,144,h,lines)
        for a,b in zip(stages,stages[1:]):
            f.arrow([(x+72,a[0]+a[1]),(x+72,b[0])])
    f.text(180, 756, "SMT는 구성한 경우에 적용한다.", 14)
    f.text(180, 780, "단계마다 별도 서버·JVM이 생기지 않는다.", 14)
    f.save()


def snapshot():
    f = Figure("fig-15-snapshot-streaming.svg", 800, "Initial snapshot과 WAL streaming의 시간 관계", "주문 104의 일관된 기준 상태는 CREATED다. Connector가 기준 WAL 위치 L0를 확보하고 consistent snapshot을 읽는 동안 DB에서 PAID 변경이 커밋된다. Snapshot 완료 뒤 기준 L0와 연결된 streaming에서 PAID update 이벤트를 전달한다. 기본적인 consistent initial snapshot의 설명이며 모든 snapshot mode가 동일한 보장과 재개 계약을 갖지는 않는다.")
    f.text(180,32,"Snapshot 중 변경도 뒤에서 읽는다",18,True)
    f.text(180,56,"가상 주문 104 · consistent initial snapshot",14)
    f.text(108,100,"DB · PostgreSQL",15,True)
    f.text(268,100,"Connector",15,True)
    f.arrow([(16,124),(16,684)])
    f.text(20,716,"시간 ↓",14,anchor="start")
    f.box(40,124,136,80,["기준 상태","104: CREATED"])
    f.box(196,124,144,80,["기준 WAL 확보","LSN = L0"])
    f.box(192,232,152,236,[],boundary=True,dashed=True)
    f.text(268,260,"consistent snapshot",14,True)
    f.box(200,280,136,96,["기준 상태 읽기","CREATED","read · op=r"])
    f.text(268,440,"snapshot 진행 중",14)
    f.box(40,328,136,96,["다른 트랜잭션","PAID로 변경","commit → WAL"])
    f.arrow([(268,204),(268,232)])
    f.arrow([(176,164),(184,164),(184,328),(200,328)], dashed=True)
    f.arrow([(108,204),(108,328)])
    f.box(196,496,144,56,["snapshot 완료"])
    f.arrow([(268,468),(268,496)])
    f.box(196,584,144,96,["streaming","기준 L0부터 읽기","PAID · op=u"])
    f.arrow([(268,552),(268,584)])
    f.arrow([(108,424),(108,632),(196,632)],dashed=True)
    f.text(108,548,"변경 로그 유지",14)
    f.text(108,572,"뒤에서 전달",14)
    f.text(180,744,"기준 snapshot과 후속 update는 다른 이벤트다.",14)
    f.text(180,768,"모든 snapshot mode의 보장이 같지는 않다.",14)
    f.save()


def outbox():
    f = Figure("fig-16-outbox-boundaries.svg", 936, "Outbox의 세 저장 경계와 포인트 소비", "원본 DB에서는 orders와 outbox를 한 트랜잭션으로 커밋한다. 별도 relay가 Kafka에 발행하며 재전달할 수 있다. 포인트 consumer는 목적지 DB에서 processed_event의 event ID unique 제약과 포인트 적립을 한 트랜잭션으로 묶는다. 업무 성공 뒤 Kafka 오프셋을 커밋하며 그 전 실패하면 다시 처리할 수 있다. 세 저장 경계 전체를 묶는 전역 원자성은 없다.")
    f.text(180,32,"Outbox는 전역 트랜잭션이 아니다",18,True)
    f.text(180,56,"가상 사례 · 포인트 적립 consumer",14)
    f.box(28,88,304,140,["① 원본 DB · 주문 서비스", "한 DB transaction", "orders + outbox", "함께 commit 또는 rollback"],boundary=True)
    f.box(64,276,232,72,["Relay · 별도 실행 주체","polling 또는 CDC로 읽고 발행"])
    f.box(28,400,304,80,["② Kafka · 저장·복제 경계","원본·목적지 DB와 별도 커밋"],boundary=True)
    f.box(64,536,232,72,["Consumer · 포인트 적립","event ID로 중복 처리 판정"])
    f.box(28,664,304,140,["③ 목적지 DB · 한 transaction","processed_event 기록 (ID unique)","+ 포인트 적립", "두 작업을 함께 commit 또는 rollback"],boundary=True)
    for start,end in [(228,276),(348,400),(480,536),(608,664)]:
        f.arrow([(180,start),(180,end)])
    f.text(180,256,"커밋된 outbox 읽기",14)
    f.text(180,376,"발행 후 checkpoint 전 실패 → 재전달 가능",14)
    f.text(180,512,"Kafka 레코드 소비",14)
    f.text(180,636,"이미 처리한 ID는 적립을 다시 하지 않음",14)
    f.text(180,836,"목적지 성공 뒤 Kafka 오프셋 commit",14,True)
    f.text(180,860,"그 전에 실패하면 재수신·재처리가 가능하다.",14)
    f.text(180,896,"①·②·③ 전체를 묶는 원자성은 없다.",15,True)
    f.text(180,920,"일반 at-least-once 전달을 가정한다.",14)
    f.save()


def main():
    runtime()
    record_path()
    snapshot()
    outbox()


if __name__ == "__main__":
    main()
